name=input("Enter Youy name :")
branch=input("Enter Your branch :")
gender=input("Enter Your gender :")
collegename=input("Enetr Your College name :")
age=int(input("Enter Your age :"))
print("Entered Name is :-",name)
print("Entered Branch is :-",branch)
print("Entered Gender is :-",gender)
print("Entered College name is :-",collegename)
print("Entered Age is :-",age)
